image: Ubuntu1804 # образ для сборки

stack: node 14 # окружение

branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

install:
  # install modules
  - npm install

build: off # отключаем встроенную в appveyor систему сборки

test_script:
  - npm run lint && npm test # скрипт тестирования